name = "examination-portal-api"
main = "src/index.js"
compatibility_date = "2025-01-01"

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "examination-db"
database_id = "77ee1a28-b01d-4f64-99ed-281d3d0378f9"
